### ISSUE TITLE
String UTF8 encoding broken in annotations

### ISSUE THREAD

**Issue by vincent-tr** [YReshetko/go-annotation#29]
If we specify a string value which contains non-ASCII characters in an annotation, its value is wrongly encoded:

```golang
// @Annotation(property="Hello, 世界")
```

Output value:
`"Hello, ä¸ç"`

This seems to come from the lexer, which split the string byte by byte, then reassemble it by converting each byte alone into a string:
https://github.com/YReshetko/go-annotation/blob/master/internal/parser/lexer.go#L104

**Comment by YReshetko** [comment]
Hey. This is fixed now with v0.1.6
Thanks
