### ISSUE TITLE
more type parameters resolved

### ISSUE THREAD

**Issue by bincooo** [YReshetko/go-annotation#34]
'p.expectPeekToken' whether the 'bool', 'number' parameters can be resolved?

**Comment by YReshetko** [comment]
Hello.
Well, if you care about resolving non-string literals exactly in parser, for example: @SomeAnnotation(param=false), then no. Parser emits panic in such case. Parameter value must be a string literal.

If you care about defining non-string fields for a structure that represents an annotation, then the 'bool' or 'numeric' value will be paresed an injected correctly [here](https://github.com/YReshetko/go-annotation/blob/master/internal/tag/tag.go#L13):
```
type SomeAnnotation struct {
	Param bool   `annotation:"name=param,default=true"`
        IntParam int `annotation:"name=int_param,default=1"`
}
```

**Comment by bincooo** [comment]
Thank you for the answer. It works for me.

Also, is there an api to get package short names?
There may be cases where the package name and short name are different.

Like the following:
package: `"bincooo/model"`
alias: `"mod"`

file: `model/model.go`
```golang
package "mod"

import (
    xxx
)
```

When debugging, it is found that the astFile in node.Lookup() has this information:
<img width="514" alt="Screenshot 2024-10-17 at 20 23 21" src="https://github.com/user-attachments/assets/23a3ce1e-c8bd-470e-9150-0bc93a5d2c10">


But I don't know how to get it in the code...

**Comment by bincooo** [comment]
Thank you for the answer. It works for me.
